<p style="text-align:center">
    <a href="https://www.linkedin.com/company/mt-learners/?viewAsMember=true" target="_blank">
    <img src="https://github.com/Mr-MeerMoazzam/Mr-MeerMoazzam/blob/main/Untitled-2.jpg?raw=true" width="150" alt="MT Learners"  />
    </a>
</p>

In [1]:
#Fuzzy c means clustering algorithm
import numpy as np, numpy.random
from scipy.spatial import distance

In [3]:
X = np.array([
        [1,1,2,1], 
        [2,1,2,3], 
        [2,2,4,5], 
        [50,42,2,83],
        [51,43,1,82],
        [51,44,3,89],
        [53,40,8,80]])

k = 2
p = 5
# Print the number of data and dimension 
n = len(X)
d = len(X[0])
addZeros = np.zeros((n, 1))
X = np.append(X, addZeros, axis=1)
print("The FCM algorithm: \n")
print("The training data: \n", X)
print("\nTotal number of data: ",n)
print("Total number of features: ",d)
print("Total number of Clusters: ",k)

The FCM algorithm: 

The training data: 
 [[ 1.  1.  2.  1.  0.]
 [ 2.  1.  2.  3.  0.]
 [ 2.  2.  4.  5.  0.]
 [50. 42.  2. 83.  0.]
 [51. 43.  1. 82.  0.]
 [51. 44.  3. 89.  0.]
 [53. 40.  8. 80.  0.]]

Total number of data:  7
Total number of features:  4
Total number of Clusters:  2


In [5]:
# Create an empty array of centers
C = np.zeros((k,d+1))
print(C)

# Randomly initialize the weight matrix
weight = np.random.dirichlet(np.ones(k),size=n)
print("\nThe initial weight: \n", np.round(weight,2))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

The initial weight: 
 [[0.86 0.14]
 [0.59 0.41]
 [0.68 0.32]
 [0.42 0.58]
 [0.22 0.78]
 [0.15 0.85]
 [0.69 0.31]]


In [6]:
for it in range(3): # Total number of iterations
    
    # Compute centroid
    for j in range(k):
        denoSum = sum(np.power(weight[:,j],2))
        
        sumMM =0
        for i in range(n):
            mm = np.multiply(np.power(weight[i,j],p),X[i,:])
            sumMM +=mm
        cc = sumMM/denoSum
        C[j] = np.reshape(cc,d+1)
 
    #print("\nUpdating the fuzzy pseudo partition")
    for i in range(n):
        denoSumNext = 0
        for j in range(k):
             denoSumNext += np.power(1/distance.euclidean(C[j,0:d], X[i,0:d]),1/(p-1))
        for j in range(k):
            w = np.power((1/distance.euclidean(C[j,0:d], X[i,0:d])),1/(p-1))/denoSumNext
            weight[i,j] = w  
            
print("\nThe final weights: \n", np.round(weight,2))


The final weights: 
 [[0.52 0.48]
 [0.52 0.48]
 [0.51 0.49]
 [0.5  0.5 ]
 [0.5  0.5 ]
 [0.5  0.5 ]
 [0.5  0.5 ]]


In [7]:
for i in range(n):    
    cNumber = np.where(weight[i] == np.amax(weight[i]))
    X[i,d] = cNumber[0]
    
print("\nThe data with cluster number: \n", X)

SSE = 0
for j in range(k):
    for i in range(n):
        SSE += np.power(weight[i,j],p)*distance.euclidean(C[j,0:d], X[i,0:d])

print("\nSSE: ",np.round(SSE,4))


The data with cluster number: 
 [[ 1.  1.  2.  1.  0.]
 [ 2.  1.  2.  3.  0.]
 [ 2.  2.  4.  5.  0.]
 [50. 42.  2. 83.  1.]
 [51. 43.  1. 82.  1.]
 [51. 44.  3. 89.  1.]
 [53. 40.  8. 80.  1.]]

SSE:  25.6798


## Thank you
## Author

<a href="https://www.linkedin.com/in/muhammad-bilal-afzal-95b33323b/">Muhammad Bilal </a>

<div data-mime-type="text/markdown" class="jp-RenderedHTMLCommon jp-RenderedMarkdown jp-MarkdownOutput">
<hr>

<h2></h2><h3 align="center"> © <a href="https://www.linkedin.com/company/mt-learners/">Mt Learners</a> 2022. All rights reserved. </h3><h3></h3>

</div>